replicaCount: 2

image:
  tag: dev-latest

config:
  LOG_LEVEL: debug
  ENVIRONMENT: dev

autoscaling:
  minReplicas: 2
  maxReplicas: 6

ingress:
  hosts:
    - host: sample-app.dev.platform.internal
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sample-app-tls
      hosts: [sample-app.dev.platform.internal]
