{{- if and .Values.envFromSecret .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else if .Values.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "managed-by-csi-driver"
{{- end }}
