apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../projects/platform-project.yaml
  - ../../projects/applications-project.yaml
  - ../../applications/monitoring.yaml
  - ../../applications/external-secrets.yaml
  - ../../applications/gatekeeper.yaml
  - ../../applications/velero.yaml
  - ../../applications/sample-app-uat.yaml

commonLabels:
  environment: uat
